colorScheme = "avocado"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
mainSections = [ "posts" ]
firebase = { }
fathomAnalytics = { }
verification = { }
enableA11y = ""
replyByEmail = true
enableStructuredBreadcrumbs = true
fingerprintAlgorithm = "sha512"
hotlinkFeatureImage = true

[header]
layout = "basic"

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true
showMenu = "Enable"

[homepage]
layout = "profile"
showRecent = true
showRecentItems = 5
showMoreLink = true
showMoreLinkDest = "/blowfish_lite/posts"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = false

[article]
showDate = true
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "basic"
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showAuthorsBadges = true
showWordCount = true
showSummary = true
sharingLinks = [
  "linkedin",
  "twitter",
  "whatsapp",
  "pinterest",
  "reddit",
  "facebook",
  "email"
]
showAuthorBottom = true

[list]
showBreadcrumbs = false
showSummary = true
showTableOfContents = false
showCards = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = true
showHero = "show"

[sitemap]
excludedKinds = [ ]

[taxonomy]
showTermCount = true

[term]
heroStyle = "thumbAndBackground"
