#:schema node_modules/wrangler/config-schema.json
name = "nautilus"
compatibility_date = "2026-01-18"

# In 2026, 'assets' is a top-level object
[assets]
directory = "./public"
binding = "ASSETS"

[vars]
HUGO_VERSION = "0.154.5"

[build]
# This is the 'Sovereign' way: let Wrangler run the script
command = "chmod +x build.sh && ./build.sh"
